-- Plattegrond Studio — accounts, plans and renders.
--
-- Everything here is owned by exactly one user. There are no teams yet, so every
-- policy is the same shape: `owner_id = auth.uid()`. When organisations land,
-- that predicate is the one thing that changes, which is why nothing else in the
-- schema encodes ownership.
--
-- Apply with:  supabase db push        (or paste into the SQL editor)

-- ─────────────────────────────────────────────────────────────────────────────
-- profiles — our own row per account, mirrored from auth.users by trigger.
--
-- auth.users is not directly readable by the client and is not ours to extend.
-- This is the table the app is allowed to join against and to show a name from.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles are readable by their owner"
  on public.profiles for select
  using ((select auth.uid()) = id);

create policy "profiles are updatable by their owner"
  on public.profiles for update
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- security definer because it writes a table the signing-up user has no rights
-- to yet; `set search_path = ''` so a schema on the caller's path cannot shadow
-- `public.profiles` and capture the insert.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─────────────────────────────────────────────────────────────────────────────
-- plans — one row per saved floor plan, document and all.
--
-- `doc` is the editor's Project object verbatim (src/engine/types.ts). The
-- columns beside it are pure derivations of that document, denormalised so the
-- library list is one cheap query that never parses a 200 KB jsonb.
--
-- Two ids on purpose. `id` is a real uuid because a primary key generated by
-- `Math.random().toString(36)` on a client with no collision check is not one.
-- `client_id` is that editor-generated id, kept because every document, every
-- exported .json file and every render already references plans by it.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.plans (
  id               uuid primary key default gen_random_uuid(),
  owner_id         uuid not null references auth.users (id) on delete cascade,
  client_id        text not null,

  name             text not null default 'Untitled plan',
  address          text not null default '',
  source_url       text not null default '',
  funda_project_id bigint,
  floor_count      integer not null default 0,

  doc              jsonb not null,

  -- the document's own updatedAt, straight off the client clock. This is the
  -- last-write-wins key, and it is deliberately NOT now(): the editor decides
  -- which of two versions is newer, and it must be able to decide that offline.
  doc_updated_at   timestamptz not null,

  -- when this row was last written, by the server. For debugging a sync, and for
  -- the day two clocks disagree badly enough that doc_updated_at stops being
  -- believable.
  synced_at        timestamptz not null default now(),
  created_at       timestamptz not null default now(),

  -- A tombstone, not a nicety. Without it, deleting a plan on one device and
  -- then opening a stale tab on another pushes the local copy straight back up
  -- and the plan returns from the dead. The bytes that cost money — the renders
  -- — are hard-deleted at the same moment; what survives is this small row.
  deleted_at       timestamptz
);

create unique index plans_owner_client_id_key on public.plans (owner_id, client_id);
create index plans_owner_recent_idx on public.plans (owner_id, doc_updated_at desc)
  where deleted_at is null;

alter table public.plans enable row level security;

create policy "plans are readable by their owner"
  on public.plans for select using ((select auth.uid()) = owner_id);
create policy "plans are insertable by their owner"
  on public.plans for insert with check ((select auth.uid()) = owner_id);
create policy "plans are updatable by their owner"
  on public.plans for update
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "plans are deletable by their owner"
  on public.plans for delete using ((select auth.uid()) = owner_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- renders — one row per generated image, including the ones that failed.
--
-- A failed render is kept deliberately: it holds the exact prompt and settings
-- that were refused, and the filmstrip is the only place a retry can live.
-- Hence `image_path` is nullable and `error` is a first-class column.
--
-- `provider_poll_url` lives here rather than travelling through the browser.
-- While there was one shared password that made no difference; with accounts it
-- is the whole difference between "poll my job" and "poll whatever job id I was
-- handed", and the status route now resolves it from this row.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.renders (
  id                uuid primary key default gen_random_uuid(),
  owner_id          uuid not null references auth.users (id) on delete cascade,
  plan_id           uuid not null references public.plans (id) on delete cascade,

  -- the editor's own ids again: `client_id` is the RenderRecord id the filmstrip
  -- keys on, `floor_id` and `parent_id` are ids from inside the document, which
  -- is why they are text and not foreign keys — there is no floors table.
  client_id         text not null,
  floor_id          text not null,
  parent_id         text,

  prompt            text not null,
  settings          jsonb not null default '{}'::jsonb,
  seed              bigint,
  model             text not null default '',

  status            text not null default 'pending'
                      check (status in ('pending', 'ready', 'failed')),
  error             text,

  provider_job_id   text,
  provider_poll_url text,

  -- object keys inside the private `renders` bucket, always prefixed with the
  -- owner's uuid so the storage policies below can authorise on the path alone
  image_path        text,
  thumb_path        text,
  bytes             bigint not null default 0,
  width             integer,
  height            integer,

  created_at        timestamptz not null default now(),
  settled_at        timestamptz,
  duration_ms       integer not null default 0
);

create unique index renders_owner_client_id_key on public.renders (owner_id, client_id);

-- exactly the query the filmstrip runs, and exactly the shape of the IndexedDB
-- `byFloor` index it replaces
create index renders_floor_idx on public.renders (owner_id, plan_id, floor_id, created_at desc);

-- for the poll loop, which asks "is anything still running?" on every boot
create index renders_pending_idx on public.renders (owner_id, created_at)
  where status = 'pending';

alter table public.renders enable row level security;

create policy "renders are readable by their owner"
  on public.renders for select using ((select auth.uid()) = owner_id);
create policy "renders are insertable by their owner"
  on public.renders for insert with check ((select auth.uid()) = owner_id);
create policy "renders are updatable by their owner"
  on public.renders for update
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "renders are deletable by their owner"
  on public.renders for delete using ((select auth.uid()) = owner_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- storage — the render PNGs.
--
-- Private bucket. Every object key starts with the owner's uuid, and the four
-- policies below authorise purely on that first path segment, so a signed URL is
-- the only way bytes ever leave.
--
-- 20 MB is well above a 1 MP PNG and well below anything that could be an upload
-- of something else entirely.
-- ─────────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('renders', 'renders', false, 20971520, array['image/png'])
on conflict (id) do nothing;

create policy "render objects are readable by their owner"
  on storage.objects for select
  using (
    bucket_id = 'renders'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "render objects are insertable by their owner"
  on storage.objects for insert
  with check (
    bucket_id = 'renders'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "render objects are updatable by their owner"
  on storage.objects for update
  using (
    bucket_id = 'renders'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "render objects are deletable by their owner"
  on storage.objects for delete
  using (
    bucket_id = 'renders'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
