import type { Project } from '@engine/types';
import type { RenderSettings } from '@shell/renders';

/** The database, in TypeScript. Hand-written rather than generated by the CLI:
 *  generating requires a live project to introspect, and this repo has to
 *  typecheck in CI with no credentials at all. It is the mirror of
 *  `supabase/migrations/20260816120000_init.sql` — change one, change the other.
 *
 *  `Row` is what comes back, `Insert` is what may go in (defaults optional),
 *  `Update` is a partial of that. The shape is the one `@supabase/supabase-js`
 *  expects for its `Database` generic, which is what makes `.from('plans')`
 *  return typed rows instead of `any`. */

export type RenderStatus = 'pending' | 'ready' | 'failed';

export type PlanRow = {
  id: string;
  owner_id: string;
  client_id: string;
  name: string;
  address: string;
  source_url: string;
  funda_project_id: number | null;
  floor_count: number;
  /** the editor's Project object, verbatim */
  doc: Project;
  doc_updated_at: string;
  synced_at: string;
  created_at: string;
  deleted_at: string | null;
}

export type RenderRow = {
  id: string;
  owner_id: string;
  plan_id: string;
  client_id: string;
  floor_id: string;
  parent_id: string | null;
  prompt: string;
  settings: RenderSettings;
  seed: number | null;
  model: string;
  status: RenderStatus;
  error: string | null;
  provider_job_id: string | null;
  provider_poll_url: string | null;
  image_path: string | null;
  thumb_path: string | null;
  bytes: number;
  width: number | null;
  height: number | null;
  created_at: string;
  settled_at: string | null;
  duration_ms: number;
}

export type ProfileRow = {
  id: string;
  email: string | null;
  created_at: string;
}

/* The columns the server fills in — `owner_id` from the session, everything with
   a DEFAULT — are optional on insert. Anything else is required, so a missing
   `doc` is a compile error rather than a not-null violation at runtime. */
type PlanInsert =
  Omit<PlanRow, 'id' | 'synced_at' | 'created_at' | 'deleted_at' | 'name' | 'address'
    | 'source_url' | 'funda_project_id' | 'floor_count'>
  & Partial<Pick<PlanRow, 'id' | 'synced_at' | 'created_at' | 'deleted_at' | 'name'
    | 'address' | 'source_url' | 'funda_project_id' | 'floor_count'>>;

type RenderInsert =
  Omit<RenderRow, 'id' | 'created_at' | 'settled_at' | 'settings' | 'seed' | 'model'
    | 'status' | 'error' | 'provider_job_id' | 'provider_poll_url' | 'image_path'
    | 'thumb_path' | 'bytes' | 'width' | 'height' | 'duration_ms' | 'parent_id'>
  & Partial<RenderRow>;

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: Pick<ProfileRow, 'id'> & Partial<ProfileRow>;
        Update: Partial<ProfileRow>;
        Relationships: [];
      };
      plans: {
        Row: PlanRow;
        Insert: PlanInsert;
        Update: Partial<PlanRow>;
        Relationships: [];
      };
      renders: {
        Row: RenderRow;
        Insert: RenderInsert;
        Update: Partial<RenderRow>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
}

/** The private bucket render PNGs live in. Named here rather than in the server
 *  provider module because both sides need it and that module is `server-only`. */
export const RENDER_BUCKET = 'renders';

/** Storage keys always start with the owner's uuid — the bucket's RLS policies
 *  authorise on that first path segment alone, so this function is not a
 *  convenience, it is the thing that makes the policies true. */
export const renderImagePath = (ownerId: string, renderId: string) =>
  `${ownerId}/${renderId}.png`;
export const renderThumbPath = (ownerId: string, renderId: string) =>
  `${ownerId}/${renderId}.thumb.png`;
